name: dhcpawn

deps:
  - psycopg2-binary
  - pyldap
  - sqlalchemy-utils
  - ipdb
  - pudb
  - ipaddress
  - celery
  - raven[flask]

flask_config:
  JSON_SORT_KEYS: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

docker:
  image_name: "git.infinidat.com:4567/infradev/dhcpawn"
