"""add sync table and update duplicate

Revision ID: 1800bcfab83a
Revises: 45391b03ee8a
Create Date: 2018-06-19 13:11:52.961595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1800bcfab83a'
down_revision = '45391b03ee8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('duplicate', sa.Column('dupvalue', sa.String(length=50), nullable=True))
    op.create_unique_constraint('dupvalue_constraint', 'duplicate', ['dupvalue'])
    op.drop_column('duplicate', 'valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duplicate', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('dupvalue_constraint', 'duplicate', type_='unique')
    op.drop_column('duplicate', 'dupvalue')
    op.drop_table('sync')
    # ### end Alembic commands ###
